name: Build
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: npm install and build
      run: |
        npm install
        npm run build
